# Generated by Django 5.1.4 on 2024-12-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('available_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=20)),
            ],
        ),
    ]
